---
# Label: project_login_tasks
# Title: create the Ansible tasks for logging into the application with a service account
# Mission: create the Ansible tasks for logging into the application with a service account
# Milestone: Data Backup/Restore
# Column: Data Backup/Restore

- name: Get restore site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN
