---
# Title: create the Ansible playbook for deploying the complete application to OpenShift
# Mission: create the Ansible playbook for deploying the complete application to OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

- name: Install the opendatapolicing pod on OpenShift and all dependencies
  hosts: localhost
  connection: local
  vars_files:
    - /usr/local/src/opendatapolicing-ansible/vaults/{{ VAULT_ID }}/vault
  roles: 
    - redhat_sso_openshift
    - project_postgres_openshift
    - project_zookeeper_openshift
    - project_solr_openshift
    - project_openshift
