---
# Title: create the Ansible playbook for deploying the application to OpenShift
# Mission: create the Ansible playbook for deploying the application to OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

- name: Install the opendatapolicing pod on OpenShift
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'ODP_ANSIBLE_INVENTORY') }}/vaults/{{ lookup('env', 'VAULT_ID') }}/vault"
  roles: 
    - project_openshift
